version: '0.1'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./app/:/usr/src/app
    ports:
      - 8000:8000
    env_file: 
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgressql/data/
    environment: 
      - POSTGRES_USER=CWAD
      - POSTGRES_PASSWORD=tobereplaced
      - POSTGRES_DB=cwad_db_dev
  volumes:
    postgres_data:
    